server:
  port: "9527"
  mode: "debug"

mysql:
  main:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "root"
    database: "cowboy_mall"
#  analytics:
#    host: "localhost"
#    port: "3307"
#    user: "analytics"
#    password: "password"
#    database: "analytics_db"

redis:
  main:
    host: "localhost"
    port: "6379"
    password: ""
    db: 0
#  cache:
#    host: "localhost"
#    port: "6380"
#    password: ""
#    db: 1

#elasticsearch:
#  host: "localhost"
#  port: "9200"
#  username: "elastic"
#  password: "password"

log:
  output: "stdout" #输出位置: stdout, stderr, file。默认为stdout
  level: "info"
  format: "json"
  dir: "logs" #日志文件路径 (当output为file时)
  file_prefix: "consumer" #日志文件名前缀(当output为file时)

prometheus:
  enabled: true
  port: "9528"
  metric_path: "/prom/metrics"
  namespace: "big_mall_pai"